const { pipeline } = require("@xenova/transformers");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

let clipModel = null;
let artifactModel = null;
let loadingPromise = null;

// FIFO cache
const analysisCache = new Map();
const CACHE_MAX_SIZE = 100;

/* ===============================
   LOAD MODELS (SAFE)
================================ */
async function loadImageModel() {
  if (clipModel && artifactModel) return;
  if (loadingPromise) return loadingPromise;

  loadingPromise = (async () => {
    clipModel = await pipeline(
      "zero-shot-image-classification",
      "Xenova/clip-vit-base-patch32",
      { quantized: true }
    );

    artifactModel = await pipeline(
      "image-classification",
      "Xenova/vit-base-patch16-224",
      { quantized: true }
    );

    console.log("✅ Multi-Model Image Detection System Loaded");
  })();

  await loadingPromise;
  loadingPromise = null;
}

/* ===============================
   HELPER FUNCTIONS
================================ */
function clamp(v, min = 0, max = 1) {
  return Math.max(min, Math.min(max, v));
}

function calculateImageEntropy(buffer) {
  const sampleSize = Math.min(buffer.length, 1024 * 1024);
  
  // Guard: empty buffer
  if (sampleSize === 0) return 0;
  
  const freq = {};
  for (let i = 0; i < sampleSize; i++) {
    freq[buffer[i]] = (freq[buffer[i]] || 0) + 1;
  }
  
  let entropy = 0;
  const len = sampleSize;
  for (let key in freq) {
    const p = freq[key] / len;
    entropy -= p * Math.log2(p);
  }
  
  return entropy / 8;
}

function getFileHash(buffer) {
  return crypto.createHash("sha256").update(buffer.subarray(0, 8192)).digest("hex");
}

/* ===============================
   METADATA ANALYSIS (BUFFER-BASED)
================================ */
function metadataScore(buffer, ext) {
  const sampleBuffer = buffer.subarray(0, 4096);
  
  let risk = 0;
  let signals = [];
  
  const sizeKB = buffer.length / 1024;
  if (sizeKB < 50) {
    risk += 0.15;
    signals.push("Suspiciously small file");
  } else if (sizeKB > 10000) {
    risk += 0.1;
    signals.push("Unusually large file");
  }

  const headerSignatures = {
    jpg: { bytes: [0xFF, 0xD8, 0xFF], depth: 3 },
    jpeg: { bytes: [0xFF, 0xD8, 0xFF], depth: 3 },
    png: { bytes: [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A], depth: 8 },
    gif: { bytes: [0x47, 0x49, 0x46, 0x38], depth: 4 },
    webp: { 
      bytes: [0x52, 0x49, 0x46, 0x46], 
      depth: 4,
      extendedCheck: (buf) => buf[8] === 0x57 && buf[9] === 0x45 && buf[10] === 0x42 && buf[11] === 0x50
    }
  };

  const sigData = headerSignatures[ext.replace('.', '')];
  if (sigData) {
    // Guard: buffer length check before indexing
    const matches = sampleBuffer.length >= sigData.depth &&
      sigData.bytes.every((byte, i) => sampleBuffer[i] === byte);
      
    if (!matches) {
      risk += 0.25;
      signals.push("File header mismatch");
    } else if (sigData.extendedCheck && sampleBuffer.length >= 12 && !sigData.extendedCheck(sampleBuffer)) {
      risk += 0.15;
      signals.push("Extended header validation failed");
    }
  }

  const entropy = calculateImageEntropy(buffer);
  if (entropy > 0.85) {
    risk += 0.2;
    signals.push("High entropy patterns");
  } else if (entropy < 0.3) {
    risk += 0.15;
    signals.push("Low entropy compression");
  }

  const bufferStr = sampleBuffer.toString('utf-8', 0, Math.min(sampleBuffer.length, 4096));
  const aiSignatures = [
    'StableDiffusion', 'Midjourney', 'DALL-E', 'AI Generated',
    'Generated by', 'Created with AI', 'Adobe Firefly',
    'GAN', 'VAE', 'Diffusion'
  ];
  
  aiSignatures.forEach(sig => {
    if (bufferStr.includes(sig)) {
      risk += 0.4;
      signals.push(`AI signature detected: ${sig}`);
    }
  });

  return { 
    score: clamp(risk), 
    signals,
    entropy,
    fileHash: getFileHash(buffer)
  };
}

/* ===============================
   CLIP ANALYSIS
================================ */
async function clipScore(imagePath) {
  const labels = [
    "real authentic photograph",
    "AI generated synthetic image",
    "computer rendered digital art",
    "photoshopped manipulated image",
    "natural skin texture portrait",
    "smooth plastic AI portrait",
    "photorealistic image",
    "digital painting artwork",
    "3D rendered scene",
    "neural network generated art"
  ];

  const result = await clipModel(imagePath, labels);
  
  const scores = {};
  result.forEach(r => {
    scores[r.label] = r.score;
  });

  const aiIndicators = [
    "AI generated", "synthetic", "computer rendered", 
    "digital art", "smooth plastic", "neural network", "3D rendered"
  ];
  
  let maxAiScore = 0;
  let dominantLabel = "";
  
  result.forEach(r => {
    if (aiIndicators.some(ind => r.label.toLowerCase().includes(ind))) {
      if (r.score > maxAiScore) {
        maxAiScore = r.score;
        dominantLabel = r.label;
      }
    }
  });

  const realIndicators = [
    "real authentic", "natural skin", "photorealistic"
  ];
  
  let realScore = 0;
  result.forEach(r => {
    if (realIndicators.some(ind => r.label.toLowerCase().includes(ind))) {
      realScore = Math.max(realScore, r.score);
    }
  });

  let finalAiScore = maxAiScore;
  if (realScore > 0.85 && maxAiScore < 0.6) {
    finalAiScore *= 0.5;
  }

  return { 
    score: clamp(finalAiScore), 
    rawScores: scores,
    dominantLabel,
    realConfidence: realScore
  };
}

/* ===============================
   ARTIFACT DETECTION
================================ */
async function artifactScore(imagePath) {
  try {
    const result = await artifactModel(imagePath);
    
    const artifactClasses = ["digital art", "cartoon", "sketch", "graphic"];
    
    let artifactRisk = 0;
    result.forEach(r => {
      if (artifactClasses.some(c => r.label.toLowerCase().includes(c))) {
        artifactRisk = Math.max(artifactRisk, r.score);
      }
    });

    return clamp(artifactRisk * 0.3);
  } catch (err) {
    return 0;
  }
}

/* ===============================
   WEIGHTED LOG-ODDS FUSION
================================ */
function fuseScores(scores, priors = {}) {
  const priorAI = priors.aiProbability || 0.5;
  const weights = { metadata: 0.3, clip: 0.6, artifact: 0.1 };
  
  const toLogOdds = (p) => Math.log((p + 0.001) / (1 - p + 0.001));
  
  let logOdds = toLogOdds(priorAI);
  
  logOdds += weights.metadata * toLogOdds(scores.metadata);
  logOdds += weights.clip * toLogOdds(scores.clip) * 1.2;
  logOdds += weights.artifact * toLogOdds(scores.artifact) * 0.5;
  
  const temperature = 0.9;
  const fused = 1 / (1 + Math.exp(-logOdds * temperature));
  
  return clamp(fused);
}

/* ===============================
   CONFIDENCE CALIBRATION
================================ */
function calibrateConfidence(rawScore, scores) {
  const values = [scores.metadata, scores.clip, scores.artifact];
  const spread = Math.max(...values) - Math.min(...values);
  
  const agreementFactor = 1 - (spread * 0.5);
  const temperature = spread > 0.4 ? 1.3 : 1.0;
  const calibrated = Math.pow(rawScore, 1 / temperature);
  
  return clamp(calibrated * agreementFactor + rawScore * (1 - agreementFactor));
}

/* ===============================
   VERDICT BUILDER
================================ */
function buildVerdict(score, signals) {
  const confidence = score * 100;
  
  let verdict, description, severity;
  
  if (confidence >= 85) {
    verdict = "Highly Likely AI Generated";
    description = "Strong synthetic indicators with high signal agreement";
    severity = "critical";
  } else if (confidence >= 65) {
    verdict = "Likely AI Generated";
    description = "Multiple AI generation signatures detected";
    severity = "high";
  } else if (confidence >= 45) {
    verdict = "Possibly AI Generated";
    description = "Some synthetic characteristics present, inconclusive";
    severity = "medium";
  } else if (confidence >= 25) {
    verdict = "Probably Real";
    description = "Minor anomalies, likely authentic";
    severity = "low";
  } else {
    verdict = "Likely Authentic";
    description = "No significant synthetic indicators";
    severity = "none";
  }

  return { verdict, description, confidence, severity };
}

/* ===============================
   MAIN ANALYZE (FIXED)
================================ */
async function analyzeImage(imagePath, options = {}) {
  const { skipCache = false, priors = {} } = options;
  
  try {
    // CRITICAL FIX: Ensure models are loaded
    await loadImageModel();
    
    // Single file read
    const stats = fs.statSync(imagePath);
    if (stats.size > 15 * 1024 * 1024) {
      throw new Error("Image too large (max 15MB)");
    }
    
    const buffer = fs.readFileSync(imagePath);
    const ext = path.extname(imagePath).toLowerCase();
    
    const cacheKey = getFileHash(buffer);
    
    if (!skipCache && analysisCache.has(cacheKey)) {
      console.log("📦 Cache hit for", path.basename(imagePath));
      return analysisCache.get(cacheKey);
    }

    const metaResult = metadataScore(buffer, ext);
    
    const [clipResult, artifactResult] = await Promise.all([
      clipScore(imagePath),
      artifactScore(imagePath)
    ]);

    const rawFused = fuseScores({
      metadata: metaResult.score,
      clip: clipResult.score,
      artifact: artifactResult
    }, priors);

    const fused = calibrateConfidence(rawFused, {
      metadata: metaResult.score,
      clip: clipResult.score,
      artifact: artifactResult
    });

    const confidence = Number((fused * 100).toFixed(2));
    const verdictData = buildVerdict(fused, {
      metadata: metaResult.score,
      clip: clipResult.score,
      artifact: artifactResult
    });

    const result = {
      verdict: verdictData.verdict,
      confidence,
      description: verdictData.description,
      severity: verdictData.severity,
      riskLevel: fused > 0.7 ? "high" : fused > 0.4 ? "medium" : "low",
      
      signals: {
        metadataRisk: Number((metaResult.score * 100).toFixed(2)),
        clipAIPrediction: Number((clipResult.score * 100).toFixed(2)),
        clipRealConfidence: Number((clipResult.realConfidence * 100).toFixed(2)),
        artifactDetection: Number((artifactResult * 100).toFixed(2)),
        detectedSignatures: metaResult.signals,
        fileEntropy: Number(metaResult.entropy.toFixed(3)),
        signalAgreement: Number((1 - Math.abs(metaResult.score - clipResult.score)).toFixed(2))
      },

      modelDetails: {
        dominantLabel: clipResult.dominantLabel,
        clipRawScores: clipResult.rawScores,
        fusionMethod: "weighted_log_odds",
        calibrationApplied: true
      },

      metadata: {
        analyzedAt: new Date().toISOString(),
        fileHash: metaResult.fileHash,
        cacheKey: cacheKey.substring(0, 16) + "...",
        models: ["clip-vit-base-patch32", "vit-base-patch16-224"],
        version: "4.3-stable"
      }
    };

    if (analysisCache.size >= CACHE_MAX_SIZE) {
      const firstKey = analysisCache.keys().next().value;
      analysisCache.delete(firstKey);
    }
    analysisCache.set(cacheKey, result);

    return result;

  } catch (err) {
    console.error("Image AI detection error:", err);
    throw new Error(`Image analysis failed: ${err.message}`);
  }
}

/* ===============================
   CACHE MANAGEMENT
================================ */
function clearCache() {
  analysisCache.clear();
  console.log("🧹 Analysis cache cleared");
}

function getCacheStats() {
  return {
    size: analysisCache.size,
    maxSize: CACHE_MAX_SIZE,
    evictionPolicy: "fifo",
    keys: Array.from(analysisCache.keys()).map(k => k.substring(0, 8) + "...")
  };
}

module.exports = {
  loadImageModel,
  analyzeImage,
  clearCache,
  getCacheStats
};